server:
  port: 9090

# 数据库配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root   #你本地的数据库用户名
    password: 123456 #你本地的数据库密码
    url: jdbc:mysql://localhost:3306/xm_hospital_x?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=GMT%2b8&allowPublicKeyRetrieval=true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
key_file_path: C:\Users\Administrator\Documents\alipayKey\
# 配置mybatis实体和xml映射
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: false
alipay:
  appId: 9021000142607371
  appPrivateKey: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCBHy+fzL9buwtomhRsdpGNlncMTXyBV1bnSKaejdWg3ALF9PXCjQC8NnlEQN1GiBconSCQoDEtIIxiSX7oDuLvAyvocYAQ2S0y4AiNpKKy+hYOameYN10gA1QYt/gGGWC4gl224htRkPSACEaTHFA36ZbTiYvBinLTC7UmHxpnxaIj8ElnWCu6rfou7bmQH3txpUtWf3fsu/EIkk9XayCqU/0bDDW+U4u8moskDx0yHPd3dwbuGeOMnW8WYxSbKl+ndyqBZ2s3jiWz6B6cWimaAd7uCogydblt7DJLFHuWyhG0PQerFgecWuSUPNLJSXqimOCCcZdTClsS+9YC7mXrAgMBAAECggEARVp72Qg/jETGFvQTnkJ9YaB85xXDlzFTUz0ZibZDFXi24J73Vf0odO+JaRiyAY1dawoikKwKXePKo4w4ZuqAB8MbVWmJUQNlnJrq3TGd1iYvrKSIaiDqmyROikxeIuCEq/YR4gZGiCQkv5QyXBfsGmwUACEz+Mulaygxr30rUKr6WtNczpI8a1puKQuRaG+IIziEuY4XirmbxY5Emyn1AdncoeDRQjZBMF6AzqUfOfTTvosjrulPrqLt5/mAd195+Y0bcFRflkOUciCbg4yBAjiPI95X4ZMpXq1Vwej8V6a5aN1swRTT8b37Qvo9GM/7DVif4BpUcuxi9TAoaRmuAQKBgQC40WkS27De7Y7AQBr901KCXWBhxC4b/Ve3/tkKmQYBCPs+fb76D24RutBIqNO5RJZJQe/z1zLjmcLQKYfOpQJgGghLbFIlRn2ewtuFmxiLPNI9CSKqjYACiOZYcwR1NS8z+HT+dxr/5FzZfIiYHek39C5ISSkIxm1mY+G1TP4c6wKBgQCy2kWWqN3uZk+684QT5vl2Sr4sv06Uj2/PxF2J/y6Kw15TjOCHn2UZYTcOKWqppEMoRpFoPFsZ7S1OL7eVdViEmmCpNiynrCREUBnFVGy7u4Gry9V1+4KA6XB99hBI70uD5ijZu0vQKOfzCuwtF114A/6WvCEORlNM8kcJ28qbAQKBgQCHdh2gj9uEmfPuX04pStGH8a7qGaN+KmM33hfw15X5/j5AYGQw3kxbvGRbTTrZ6TaJ/UVFoS6Qeau7bSU4ReOG0q3PslZHMfJzAflqZPJJY8vopqB9B3eS5AqJO8xBqDivy+TceioU8qlHUyq+6/V7aILfwpfL8bxPttfBTexW/wKBgG4Nv7pYSM/0puUMCV7RxvlSPrl8MpdZt9yqIUDUBEigtT9GNbdejrBSULVnKNogWK7E1Z7FXO2UM0ekNxxBq+lUsVwOGOZIF7ztaR4yuAHA/KbA86X40LIQcwcfTaADl30fOE3aYWlCco/sTa3lbb92/ca1FsYY4hM8Fhhr5b0BAoGAC8xwnhNEL4FSZ958yP8L51ybf/AJACfvzPlaVW+cx7bKHxPU7xVLRXt1WC3+P3GskynUVRKFlUiYVddKooGZblTgoWDjbrF2kLHzpsYGIijyWEiMPMHtHee/uUUNgroKLUu3/GDvv/YaMCqy51geCNRqwpi57nUwd+T7gUKn/3A=
  alipayPublicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA8FKDzXrq6XkN12Xk7dvyiBbdNy01MwPj5SrH0TPmjsl0eMZpjrp7b0r3HgPU2o//jgGlVGI193fgKBPJ3/C24m/ln8jZM1Gr/Fa1PBCYNbfLcj/0RYIAG9ujBKv5e42ysOJa7BR/HcRq2vUkxFCwgioNzeQfTn9HEfm1M3hbuUGAR5VI6rxiCxwTDf7DMkwSWDTznSE1pn0UVbZXsQfnhiOzw8cZLL+Q/DfzmZXUA9KRgD7uDkVd80db6Ecyn8cpd2zEVPt9jP+tdW8Jc+gIkti+eSryROWxMrfmTiEzqxJHHkJy0Fk8UsohRHOzqCHlpc5iwF0aF6uiIe1s04TjTwIDAQAB
  notify_url: http://rp9m6r.natappfree.cc/pay/notify
  gateway: https://openapi-sandbox.dl.alipaydev.com/gateway.do
# 分页
pagehelper:
  helper-dialect: mysql
  reasonable: false
  support-methods-arguments: true
  params: count=countSql
  page-size-zero: true